spring:

  application:
    name: northwind
  datasource:
    # Replace localhost, 5432, and my_database with your specific database details
    url: jdbc:postgresql://localhost:5432/northwind_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Options: none, validate, update, create, create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true